inherit_gem:
  gc_ruboconfig: rubocop.yml

require:
  - rubocop-rspec

AllCops:
  Exclude:
    - vendor/**/*
  TargetRubyVersion: 3.1

Style/Documentation:
  Enabled: false

Style/SignalException:
  EnforcedStyle: "only_raise"

Layout/DotPosition:
  EnforcedStyle: "trailing"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*_spec.rb"

RSpec/NestedGroups:
  Max: 5

Gemspec/RequiredRubyVersion:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5
