version: 2

references:
  steps: &steps
    - checkout

    # CircleCI's Ruby images have Git installed, but the JRuby images lack it, so let's
    # make sure it's installed
    - run: apt-get update && apt-get install -y git

    - type: cache-restore
      key: prius-bundler-{{ checksum "prius.gemspec" }}

    - run: gem install bundler -v 2.0.1

    - run: bundle install --path vendor/bundle

    - type: cache-save
      key: prius-bundler-{{ checksum "prius.gemspec" }}
      paths:
        - vendor/bundle

    - type: shell
      command: |
        bundle exec rspec --profile 10 \
                          --format RspecJunitFormatter \
                          --out /tmp/test-results/rspec.xml \
                          --format progress \
                          spec

    - type: store_test_results
      path: /tmp/test-results

    - run: bundle exec rubocop
jobs:
  build-ruby26:
    docker:
      - image: ruby:2.6
    steps: *steps
  build-ruby27:
    docker:
      - image: ruby:2.7
    steps: *steps
  build-ruby3:
    docker:
      - image: ruby:3
    steps: *steps
  build-jruby93:
    docker:
      - image: jruby:9.3
    steps: *steps

workflows:
  version: 2
  tests:
    jobs:
      - build-ruby26
      - build-ruby27
      - build-ruby3
      - build-jruby93
